### ISSUE TITLE
No Result

### ISSUE THREAD

**Issue by moloch--** [actumn/celery.node#21]
I have a simple `add` task I'm trying to call from Python. I can successfully call the worker and pass arguments, and the worker appears to succeed and return a result, but the Python `result.get()` never returns:

```python
@app.task(name='add')
def add(a, b):
        pass

def start():
        app_log.info("Sending task ...")
        result = add.apply_async((1,2,), queue='c2')
        foo = result.get(10000)
        app_log.info("Foo = %r", foo)
        self.write(str(foo))
```

JavaScript worker code:

```javascript
const celery = require('celery-node');

const broker = "redis://redishost:6379/0";
const queue = "c2";

const worker = celery.createWorker(broker, broker, queue);
worker.register("add", (a, b) => {
    return a + b;
});
worker.start();
```

<img width="1102" alt="Screen Shot 2020-08-01 at 3 19 24 PM" src="https://user-images.githubusercontent.com/875022/89109887-d534f300-d40a-11ea-830a-f3d155a5861f.png">

**Comment by actumn** [comment]
Thank you for the report. 
But unfortunately, I cannot reproduce the issue you described.
Can you share more information such as python celery version or celery app configuration?

**Comment by moloch--** [comment]
```
$ celery --version
4.4.6 (cliffs)
```

Celery config:

```
from celery import Celery
from kombu import Exchange, Queue
from tornado.options import options

from tasks.helpers import redis_url

DEFAULT_QUEUE = 'default'
C2_QUEUE = 'c2'

def broker_url() -> str:
    return redis_url(options.redis_broker_db)

app = Celery('hive', backend='rpc', broker=broker_url())
app.conf.update(
    task_serializer='json',
    accept_content=['json'],
    result_serializer='json',
    result_expires=3000,
)

```

**Comment by actumn** [comment]
I see. `rpc` result backend is not supported yet now in celery.node. 
If you want to get async result, why don't you use redis backend?
Like below
```python
from celery import Celery

app = Celery( 
    broker="redis://redishost:6379/0",
    backend="redis://redishost:6379/0"
)

@app.task(name='add')
def add(x, y):
    pass

def start():
    print("sending task...")
    result = add.apply_async((1,2,), queue='c2')
    foo = result.get(10000)
    print('foo =', foo)

start()
```

**Comment by moloch--** [comment]
Ahh okay, I had a misunderstanding of how the `backend` parameter worked. It's working now, thanks for the help!
