### ISSUE TITLE
TypeError: body is not iterable

### ISSUE THREAD

**Issue by ardian-c** [actumn/celery.node#29]
Hi, 

I have a client with the following content: 
```javascript
const message = data.content.toString(); // {'url': 'some url'}
const task = client.createTask('tasks.some-task'); 
const result = task.applyAssync([message]);
```

And the worker:
```javascript
worker.register('tasks.some-task', (data) => {
   console.log('data: ', data);
   return data;
});
```

The error appears in `dist/app/worker.js` at this part `const [args, kwargs /*, embed */] = body;`, link below: 
https://github.com/actumn/celery.node/blob/99979974f95e74e946ff37d9153f73efd666ccba/src/app/worker.ts#L131

If the message is a JSON structure, why `args` and `kwargs` are expected to be there.  
What am I missing? 

Thanks!

**Comment by actumn** [comment]
Hi.

Unfortunately, I couldn't reproduce any TypeError you described.

The below described what I tested.
- Client
```js
const celery = require("celery-node");

const client = celery.createClient("amqp://", "amqp://");

const message = `{'url': 'some url'}`
const task = client.createTask('tasks.some-task'); 
const result = task.applyAsync([message]);
result.get().then(data => {
  console.log(data);
  client.disconnect();
});
```
- Worker
```js
const worker = celery.createWorker("amqp://", "amqp://");
worker.register('tasks.some-task', (data) => {
  console.log('data: ', data);
  return data;
});
worker.start();
```

**Comment by ardian-c** [comment]
Hi, 

The issue is now solved, my problem was that I was connecting to some queue in the worker, while the client pushed the task queue somewhere else. Changing the configuration for worker made it work fine. 

Thanks.

**Comment by actumn** [comment]
Glad that you solved it :)
