### ISSUE TITLE
Question: Is there any method corresponding to node-celery call() method in celery.node?

### ISSUE THREAD

**Issue by akira-toyoshima** [actumn/celery.node#40]
## Description

Is there any method corresponding to node-celery `call()` method in celery.node?
https://github.com/mher/node-celery/blob/master/celery.js#L246

I think it is `sendTask()` in my mind.

Thank you

**Comment by actumn** [comment]
Hi.
Yeah, you can use `sendTask()` to call without `createTask()`.
For example,
```javascript
client.sendTask("add", [1, 2]);
client.sendTask("add_kwargs", [], { a: 3, b: 4 });
client.sendTask("task_id_specified", [], {}, "some_task_id");
```

If you have any questions or feature requests, feel free to ask me.

**Comment by akira-toyoshima** [comment]
@actumn Thank you so much for your fast replying.
I'll try it! Thank you.
