### ISSUE TITLE
Contributor License Agreement

### ISSUE THREAD

**Issue by travis5555** [actumn/celery.node#42]
Hi - we've created a private fork and made updates to address a number of connection and promise-based issues and would like to submit a pull request. Is there a generic Contributor License Agreement you can share that we can fill out so we can send this pull request for review please? Apologies if you have already provided this. Thank you

**Comment by actumn** [comment]
Hi.
It sounds awesome you're planning to submit some contributions. 
There's no CLA for `celery.node`. No limits, no obligation.
So feel free to make any pull requests or contributions.
Thank you.
