### ISSUE TITLE
asyncResult.get() resolves when data is not ready

### ISSUE THREAD

**Issue by harrybaines** [actumn/celery.node#43]
## Description

* **What is the current behavior?**

Calling `asyncResult.get()` can return something like:

`{ pid: 10, hostname: 'celery@5d9200725862' }`

when the task has been started. 

* **What is the expected behavior?**

Ideally we would want to await the completion of a task to get the intended task result. So calling `asyncAwait.get()` should await the completion of the task and return the result.

* **Please tell us about your environment:**
  
  - Version: 0.5.3
  - OS: macOS Catalina
  - Language: ES6

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Related issue #38. I believe a caching issue was mentioned at some point?

**Comment by actumn** [comment]
Hi. Sorry for the late.
Thank you for the report, and I'll check it!

**Comment by actumn** [comment]
@chilts fixed it and I published the package as v0.5.4.
Please check it.
