### ISSUE TITLE
amqps not supported? 

### ISSUE THREAD

**Issue by Nkadze** [actumn/celery.node#53]
Just accessing with amqps throws error `Unsupported type: amqps` 
Error comes from `backends/index.ts` which is defining `const supportedProtocols = ["redis", "amqp"];`

**Comment by higgins** [comment]
@Nkadze I was able to connect to a Rabbit cluster on AWS MQ which only supports `amqps` connections with a few small changes: https://github.com/actumn/celery.node/pull/72

**Comment by Nkadze** [comment]
@higgins did something similar on my fork, Thanks for pushing it 🍺
