### ISSUE TITLE
Add "rediss://" support

### ISSUE THREAD

**Issue by dethos** [actumn/celery.node#79]
## Description
**What is the motivation / use case for changing the behavior?**

Currently the supported protocols are:
> const supportedProtocols = ["redis", "amqp", "amqps"];

it would also be nice to add support for TLS connections to a redis broker and backend.

As far as I can tell, the [Redis library used for this package already supports TLS](https://github.com/luin/ioredis#connect-to-redis), so this shouldn't be a big change  

**Proposed Behavior**

Accept `rediss://` urls for broker and backend

**Comment by actumn** [comment]
Thanks to @guywillett, it looks solved by #83.
Published as 0.5.9, so I'm gonna close it.
Feel free to reopen when the issue reoccurs.
