### ISSUE TITLE
asyncResult created from task ID does not return anything

### ISSUE THREAD

**Issue by vladimirtiukhtin** [actumn/celery.node#81]
## Description

I do this
```js
const taskIdResult = celery.client.asyncResult("95be403e-4b67-4edf-82e8-dbbae9f1c99f");
result = taskIdResult.get()
console.log(result)
```

but get nothing. At the same time I can print taskIdResult with no problem
```js
AsyncResult {
  taskId: '95be403e-4b67-4edf-82e8-dbbae9f1c99f',
  backend: RedisBackend {
    redis: Redis {
      options: [Object],
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      scriptsSet: {},
      addedBuiltinSet: Set(0) {},
      commandQueue: [Denque],
      offlineQueue: [Denque],
      connectionEpoch: 1,
      connector: [StandaloneConnector],
      retryAttempts: 0,
      _addedScriptHashes: {},
      _autoPipelines: Map(0) {},
      _runningAutoPipelines: Set(0) {},
      _addedScriptHashesCleanInterval: Timeout {
        _idleTimeout: 60000,
        _idlePrev: [TimersList],
        _idleNext: [TimersList],
        _idleStart: 4528,
        _onTimeout: [Function (anonymous)],
        _timerArgs: undefined,
        _repeat: 60000,
        _destroyed: false,
        [Symbol(refed)]: true,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 14,
        [Symbol(triggerId)]: 13
      },
      status: 'connecting',
      condition: [Object],
      [Symbol(kCapture)]: false
    }
  },
  _cache: null
}
```
Task exists in celery and is succeeded. Please help

**Comment by actumn** [comment]
Hey, @vladimirtiukhtin
Thank you for your attention to the project.

About how to use result of task, please refer to below
### As-Is
```js
const taskIdResult = celery.client.asyncResult("95be403e-4b67-4edf-82e8-dbbae9f1c99f");
result = taskIdResult.get()
console.log(result)
```

### To-Be

As the AsyncResult#get() returns `Promise<any>` type, you should use with `Promise.then` or async-await scope.
- Promise.then()
```js
const taskIdResult = celery.client.asyncResult("95be403e-4b67-4edf-82e8-dbbae9f1c99f");
taskIdResult.get().then(data -> console.log(data);
```

- Async-Await
```js
async function a() {
  const taskIdResult = celery.client.asyncResult("95be403e-4b67-4edf-82e8-dbbae9f1c99f");
  const result = await taskIdResult.get();
  console.log(result);
}
```

If the issue continues, feel free to comment here :)

**Comment by vladimirtiukhtin** [comment]
Thanks for the prompt response @actumn
I tried that. It just does not look like it returns a promise. applyAsync does and I can use "then" on it and get result back, but asyncResult does not

**Comment by vladimirtiukhtin** [comment]
Hey @actumn, have you had a chance to look at issue? I tried recent 0.5.9 release and it is still affected

**Comment by vladimirtiukhtin** [comment]
Hey @actumn I tried recent 0.5.9 release. If I print taskIdResult.get() it returns a promise which however never gets resolved even if task in "SUCCESS" status

**Comment by vladimirtiukhtin** [comment]
Turns out it was my misunderstanding of how "then" works. I was pretty confident that program waits at where "then" is placed. Switching to "await" fixed it

**Comment by actumn** [comment]
> I was pretty confident that program waits at where "then" is placed. Switching to "await" fixed it

Happy to hear that :)
